---

- name: APT | Install localtunnel dependencies
  apt:
    name: "{{ packages }}"
    state: latest
    dpkg_options: 'force-confnew,force-confdef'
    autoclean: yes
    autoremove: yes
    update_cache: yes
    cache_valid_time: 3600
  vars:
    packages:
    - supervisor

- name: install localtunnel
  npm:
    name: localtunnel
    global: yes

- name: add localtunnel unit file
  template:
    src: localtunnel.service.j2
    dest: /etc/systemd/system/localtunnel.service
    mode: 0644

- name: reload systemd
  systemd:
    daemon_reload: yes

- name: enable localtunnel
  systemd:
    name: localtunnel
    enabled: yes

- name: start localtunnel
  systemd:
    name: localtunnel
    state: started


...
